apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: mayur619/payments:latest
        env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name : NATS_CLUSTER_ID
              value: 'ticketing'
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: REZPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: rezpay-secret
                  key: REZPAY_KEY_SECRET
            - name: REZPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: rezpay-id
                  key: REZPAY_KEY_ID

---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments 
  ports:
  - name: payments
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
