name: deploy-menifest
on:
  push:
    branches:
      - master
    paths: -"infra/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITAL_OCEAN}}
      - run: doctl kubernetes cluster kubeconfig save ticketting
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
