name: test
on:
  pull_request:
    paths:
      - "payments/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: payments

      - name: Run tests
        run: npm run test:ci
        working-directory: payments

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: payments/test-results/

      - name: Debug environment
        run: |
          node -v
          npm -v
          ls -la payments
